import json

BATCH = "/home/doblek/open-bfme1/BFME-Translation/.agent/batches/rotwk-run1-5-4855c4dbd3b7.json"

TRANS = {
"CONTROLBAR:TooltipPurchaseCustomCampKeepTacticsLvls": "Aumenta el nivel de la ciudadela en 1",
"CONTROLBAR:SpecialAbilityGrantExpPoints": "Necesitamos más experiencia (&W)",
"CONTROLBAR:TooltipSpecialAbilityGrantExpPoints": "Otorga 300 de experiencia a la Ciudadela\\n Tiempo de reutilización: 60s",
"CONTROLBAR:PurchaseCustomTactic1": "Tácticas 1 Nivel 1 (&D)",
"CONTROLBAR:PurchaseCustomTactic4": "Tácticas 1 Nivel 2 (&D)",
"CONTROLBAR:PurchaseCustomTactic7": "Tácticas 1 Nivel 3 (&D)",
"CONTROLBAR:ToolTipPurchaseCustomTactic7": "Otorga +25% de alcance de ataque y visión a las tropas (No afecta a los aliados)",
"CONTROLBAR:PurchaseCustomTactic10": "Tácticas 1 Nivel 4 (&D)",
"CONTROLBAR:ToolTipPurchaseCustomTactic10": "Otorga +33% de daño y armadura a las tropas y a los héroes (No afecta a los aliados)",
"CONTROLBAR:PurchaseCustomTactic2": "Tácticas 2 Nivel 1 (&S)",
"CONTROLBAR:ToolTipPurchaseCustomTactic2": "Solo puedes elegir 1 rama de tácticas\\n\\nNivel 1: Otorga un descuento de -20% para las mejoras de las minas y genera una carreta con oro cerca de la mina cada minuto, que puedes vender en la ciudadela (No afecta a los aliados)",
"CONTROLBAR:PurchaseCustomTactic5": "Tácticas 2 Nivel 2 (&S)",
"CONTROLBAR:ToolTipPurchaseCustomTactic5": "Aumenta la venta de tropas en la ciudadela en +100% (No afecta a los aliados)",
"CONTROLBAR:PurchaseCustomTactic8": "Tácticas 2 Nivel 3 (&S)",
"CONTROLBAR:ToolTipPurchaseCustomTactic8": "Otorga un descuento de -25% en todas las habilidades de la tienda de habilidades (No afecta a los aliados)",
"CONTROLBAR:PurchaseCustomTactic11": "Tácticas 2 Nivel 4 (&S)",
"CONTROLBAR:ToolTipPurchaseCustomTactic11": "Otorga a la Ciudadela y a la Puerta +2500 de salud (No afecta a los aliados)",
"CONTROLBAR:PurchaseCustomTactic3": "Tácticas 3 Nivel 1 (&A)",
"CONTROLBAR:ToolTipPurchaseCustomTactic3": "Solo puedes elegir 1 rama de tácticas\\n\\nNivel 1: Otorga 5 puntos de poder y un descuento de -50% para el generador de puntos de poder (No afecta a los aliados)",
"CONTROLBAR:PurchaseCustomTactic6": "Tácticas 3 Nivel 2 (&A)",
"CONTROLBAR:PurchaseCustomTactic9": "Tácticas 3 Nivel 3 (&A)",
"CONTROLBAR:ToolTipPurchaseCustomTactic9": "Otorga 10 puntos de poder",
"CONTROLBAR:PurchaseCustomTactic12": "Tácticas 3 Nivel 4 (&A)",
"CONTROLBAR:ToolTipPurchaseCustomTactic12": "Otorga 5 puntos de poder y -33% de tiempo de reutilización para el libro de hechizos",
"CONTROLBAR:PurchaseUpgradeMinasTirithGate": "Mejorar Puerta",
"CONTROLBAR:ToolTipPurchaseUpgradeMinasTirithGate": "Aumenta los puntos de salud de la puerta en 5000",
"CONTROLBAR:PurchaseUpgradeMinasTirithWalls": "Mejorar Muros",
"CONTROLBAR:ToolTipPurchaseUpgradeMinasTirithWalls": "Las tropas en el muro reciben: 10% de daño, 15% de armadura, 10% de alcance y radio de visión\\nFunciona con todos, incluidos aliados y enemigos",
"CONTROLBAR:ToolTipPurchaseUpgradeCustomNumenorStonework": "Otorga +67% de armadura a la Ciudadela del Castillo",
"CONTROLBAR:PurchaseUpgradeCustomCastleLevel2": "Mejorar Castillo al Nivel 2 (&E)",
"CONTROLBAR:ToolTipPurchaseUpgradeCustomCastleLevel2": "Desbloquea el acceso a arqueros de élite, caballería y espadas",
"CONTROLBAR:PurchaseUpgradeCustomCastleLevel3": "Mejorar Castillo al Nivel 3 (&E)",
"CONTROLBAR:ToolTipPurchaseUpgradeCustomCastleLevel3": "Desbloquea el acceso a mini héroes y catapultas",
"CONTROLBAR:PurchaseUpgradeCustomBuildSpeed": "Industria",
"CONTROLBAR:ToolTipPurchaseUpgradeCustomBuildSpeed": "Aumenta la velocidad de producción en 50%",
"CONTROLBAR:ConstructMoneyMaker_v2Unit": "Minero enano (&W)",
"CONTROLBAR:ToolTipBuildMoneyMaker_v2Unit": "El minero enano extrae mineral y genera recursos",
"CONTROLBAR:PurchaseMoneyMaker_v2SpeedBoost": "Industriosidad enana (&D)",
"CONTROLBAR:ToolTipPurchaseMoneyMaker_v2SpeedBoost": "Permite a los mineros enanos extraer mineral 2 veces más rápido",
"CONTROLBAR:PurchasePowerPointMakerV2Upgrade1": "Ola de Guerreros Orcos (&W)",
"CONTROLBAR:ToolTipPurchasePowerPointMakerV2Upgrade1": "Invoca 10 guerreros orcos cada 60s para aplastarte",
"CONTROLBAR:PurchasePowerPointMakerV2Upgrade2": "Ola de Arqueros Orcos (&D)",
"CONTROLBAR:ToolTipPurchasePowerPointMakerV2Upgrade2": "Invoca 10 arqueros orcos cada 60s para aplastarte",
"CONTROLBAR:PurchasePowerPointMakerV2Upgrade3": "Ola de Lanzadores Haradrim (&S)",
"CONTROLBAR:ToolTipPurchasePowerPointMakerV2Upgrade3": "Invoca 10 lanzadores haradrim cada 60s para aplastarte",
"CONTROLBAR:PurchasePowerPointMakerV2Upgrade4": "Ola de Orcos Negros (&A)",
"CONTROLBAR:ToolTipPurchasePowerPointMakerV2Upgrade4": "Invoca 10 orcos negros cada 60s para aplastarte",
"CONTROLBAR:PurchasePowerPointMakerV2Upgrade5": "Ola de Troll Tamborilero (&R)",
"CONTROLBAR:ToolTipPurchasePowerPointMakerV2Upgrade5": "Invoca 1 troll tamborilero cada 60s para aplastarte",
"CONTROLBAR:PurchasePowerPointMakerV2Upgrade6": "Ola de Troll de Ataque (&T)",
"CONTROLBAR:ToolTipPurchasePowerPointMakerV2Upgrade6": "Invoca 1 troll de ataque cada 60s para aplastarte",
"CONTROLBAR:CustomHeroUpgradeMaker": "Tienda de Mejoras",
"CONTROLBAR:CustomHeroUpgradeMakerDescription": "Investiga varias mejoras para héroes",
"CONTROLBAR:CustomHeroUpgradeMakerUpgrade1": "Mejora de Arma (&W)",
"CONTROLBAR:ToolTipCustomHeroUpgradeMakerUpgrade1": "El héroe obtiene +100% de daño permanentemente",
"CONTROLBAR:CustomHeroUpgradeMakerUpgrade2": "Mejora de Armadura (&D)",
"CONTROLBAR:ToolTipCustomHeroUpgradeMakerUpgrade2": "El héroe obtiene +50% de armadura permanentemente (&D)",
}